version: "3.8"
services:
  nginx-react:
    container_name: Deverick-Frontend
    build: "https://github.com/sovheiv/Deverick-Frontend.git#main:"
    ports:
      - 8004:8004
    environment:
      NODE_ENV: production
